theme='hugo_theme_robust'
baseurl = "http://jonathan.pinlac.net/blog/"
languageCode = "en-us"
title = "Jonathan Pinlac's Blog"
author = "Jonathan Pinlac"
copyright = "© Copyright 2016, Jonathan Pinlac."

[params]
	disqusShortname = "jpinlac"

[taxonomies]
	tag = "Tags"
	category = "Categories"
