theme='hugo_theme_robust'
baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Jonathan Pinlac's Blog"
author = "Jonathan Pinlac"
copyright = "© Copyright 2016, Jonathan Pinlac."

[params]
	disqusShortname = "jpinlac"